// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS8XwfXv-D06OA5e9uogMsd1EwgKyb9as',
    appId: '1:360774236322:web:94b1a323f2737b78b23ffb',
    messagingSenderId: '360774236322',
    projectId: 'hostel-night-mess',
    authDomain: 'hostel-night-mess.firebaseapp.com',
    storageBucket: 'hostel-night-mess.firebasestorage.app',
    measurementId: 'G-YGCWEWG4T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPGImbZUrjkBlOeHtiZ7IghmQUpXt9eR8',
    appId: '1:360774236322:android:5241cae08081e0f8b23ffb',
    messagingSenderId: '360774236322',
    projectId: 'hostel-night-mess',
    storageBucket: 'hostel-night-mess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05Juc-LVWUwpDl1ZFmpZsvWCi6WnCJsY',
    appId: '1:360774236322:ios:4a30fb3d5ca284f7b23ffb',
    messagingSenderId: '360774236322',
    projectId: 'hostel-night-mess',
    storageBucket: 'hostel-night-mess.firebasestorage.app',
    iosBundleId: 'com.example.hostelNightMessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05Juc-LVWUwpDl1ZFmpZsvWCi6WnCJsY',
    appId: '1:360774236322:ios:4a30fb3d5ca284f7b23ffb',
    messagingSenderId: '360774236322',
    projectId: 'hostel-night-mess',
    storageBucket: 'hostel-night-mess.firebasestorage.app',
    iosBundleId: 'com.example.hostelNightMessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS8XwfXv-D06OA5e9uogMsd1EwgKyb9as',
    appId: '1:360774236322:web:b8fb31aa9fe08d44b23ffb',
    messagingSenderId: '360774236322',
    projectId: 'hostel-night-mess',
    authDomain: 'hostel-night-mess.firebaseapp.com',
    storageBucket: 'hostel-night-mess.firebasestorage.app',
    measurementId: 'G-LM69Z1MXPK',
  );
}
