import 'package:flutter/material.dart';
import 'signup_screen.dart'; // Import your signup screen
import 'login_screen.dart'; // Import your login screen
import 'order_screen.dart'; // Import your order screen
import 'orders_list_screen.dart'; // Import OrdersListScreen
import 'package:firebase_core/firebase_core.dart';

// Firebase options for web (replace with your own)
import 'firebase_options.dart'; // Ensure this file is generated by the Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the appropriate options for the current platform (e.g., web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // This is crucial for web
  );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'YoruGohan',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/login', // Set initial route to login
      routes: {
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/order': (context) => OrderScreen(), // Define your order screen route
        '/orders': (context) =>
            OrdersListScreen(), // Add route for OrdersListScreen
      },
    );
  }
}
